/**
 * The controlled vocabularies the seeder draws from.
 *
 * Both lists are comfortably longer than the 20 values a facet group returns,
 * so "top 20 nationalities" and "top 20 hobbies" are a real truncation of a
 * larger set rather than simply everything that exists. That matters: a facet
 * list that never truncates would not exercise the ranking at all.
 *
 * Fixed lists rather than randomly generated strings, so the values are
 * recognisable, stable across seeds, and safe to reference in tests.
 */

/** Demonyms, matching how a person would describe their own nationality. */
export const NATIONALITIES = [
  'American',
  'Argentine',
  'Australian',
  'Austrian',
  'Belgian',
  'Brazilian',
  'British',
  'Bulgarian',
  'Canadian',
  'Chinese',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'Egyptian',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'German',
  'Greek',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Kenyan',
  'Korean',
  'Latvian',
  'Lithuanian',
  'Mexican',
  'Moroccan',
  'Nigerian',
  'Norwegian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Serbian',
  'Slovak',
  'South African',
  'Spanish',
  'Swedish',
  'Swiss',
  'Turkish',
  'Ukrainian',
  'Vietnamese',
] as const;

export const HOBBIES = [
  'Archery',
  'Astronomy',
  'Baking',
  'Basketball',
  'Birdwatching',
  'Blogging',
  'Board Games',
  'Bouldering',
  'Calligraphy',
  'Camping',
  'Canoeing',
  'Ceramics',
  'Chess',
  'Cooking',
  'Crocheting',
  'Cycling',
  'Dancing',
  'Diving',
  'Drawing',
  'Embroidery',
  'Fishing',
  'Gardening',
  'Genealogy',
  'Glassblowing',
  'Golf',
  'Hiking',
  'Horse Riding',
  'Ice Skating',
  'Jewellery Making',
  'Journaling',
  'Kayaking',
  'Knitting',
  'Languages',
  'Leatherworking',
  'Magic Tricks',
  'Meditation',
  'Model Building',
  'Mountaineering',
  'Origami',
  'Painting',
  'Photography',
  'Pilates',
  'Podcasting',
  'Pottery',
  'Puzzles',
  'Reading',
  'Rowing',
  'Running',
  'Sailing',
  'Scrapbooking',
  'Sculpting',
  'Sewing',
  'Singing',
  'Skateboarding',
  'Skiing',
  'Snowboarding',
  'Squash',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Tennis',
  'Travelling',
  'Video Games',
  'Volleyball',
  'Woodworking',
  'Writing',
  'Yoga',
] as const;
